# Use the Ubuntu 20.04 as a base image
FROM ubuntu:20.04

# Set environment variables to non-interactive (this prevents some prompts)
ENV DEBIAN_FRONTEND=non-interactive

# Install required packages
RUN apt-get update && \
    apt-get install -y openmpi-bin libopenmpi-dev mpich libmpich-dev gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the default command to bash (optional)
CMD ["/bin/bash"]